// @ts-check

/**
 * The sidebar is generated from the docs folder structure. Ordering and
 * labels come from each doc's frontmatter `sidebar_position` / `title` and
 * the `_category_.json` files in each section directory.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
